name: JUnit Test Workflow

on:
  push:
    branches:
      - main  # Change to your main branch name if necessary
  pull_request:
    branches:
      - main  # Change to your main branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Change to the Java version you are using

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run JUnit tests
      run: ./gradlew test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
