/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package l2.github.actions.azizahmadov;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
